name: my_status_widget
description: A Flutter package for a custom status dotted borders widget.
version: 0.0.1
repository: https://github.com/subruzz/my_status_widget_package.git

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:


